version: "3.9"

name: gestion-taxiBrousse

services:
  postgres:
    image: postgres:17
    container_name: postgres_taxiBrousse
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: taxiBrousse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bdd:/docker-entrypoint-initdb.d

volumes:
  postgres_data: